### ISSUE TITLE
Fail to show 201 status code when created.

### ISSUE THREAD

**Issue by mak1986** [fortunejs/fortune-json-api#11]
When I try to insert the data:

```
POST /article HTTP/1.1
Content-Type: application/vnd.api+json
Accept: application/vnd.api+json

{
    "data": {
        "type":"article",
        "attributes": {
            "title": "Just another title",
            "body": "Just another body"
        }
    }
}
```

I receive 500 status code, but the data got inserted.

This is the message from the console.

```
Unhandled rejection TypeError: Cannot read property 'toString' of undefined
    at JsonApiSerializer.mapRecord (/home/makjacobsen/sandbox/fortune/node_modules/fortune-json-api/dist/lib/helpers.js:205:40)
    at /home/makjacobsen/sandbox/fortune/node_modules/fortune-json-api/dist/lib/index.js:233:39
    at Array.map (native)
    at JsonApiSerializer.showResponse (/home/makjacobsen/sandbox/fortune/node_modules/fortune-json-api/dist/lib/index.js:232:60)
    at proxyMethod (/home/makjacobsen/sandbox/fortune/node_modules/fortune/lib/serializer/singleton.js:141:54)
    at Object.showResponse (/home/makjacobsen/sandbox/fortune/node_modules/fortune/lib/serializer/singleton.js:113:12)
    at /home/makjacobsen/sandbox/fortune/node_modules/fortune/lib/dispatch/end.js:69:23
    at tryCatcher (/home/makjacobsen/sandbox/fortune/node_modules/bluebird/js/release/util.js:11:23)
    at Promise._settlePromiseFromHandler (/home/makjacobsen/sandbox/fortune/node_modules/bluebird/js/release/promise.js:489:31)
    at Promise._settlePromise (/home/makjacobsen/sandbox/fortune/node_modules/bluebird/js/release/promise.js:546:18)
    at Promise._settlePromise0 (/home/makjacobsen/sandbox/fortune/node_modules/bluebird/js/release/promise.js:591:10)
    at Promise._settlePromises (/home/makjacobsen/sandbox/fortune/node_modules/bluebird/js/release/promise.js:674:18)
    at Async._drainQueue (/home/makjacobsen/sandbox/fortune/node_modules/bluebird/js/release/async.js:125:16)
    at Async._drainQueues (/home/makjacobsen/sandbox/fortune/node_modules/bluebird/js/release/async.js:135:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/home/makjacobsen/sandbox/fortune/node_modules/bluebird/js/release/async.js:16:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
```

This is my datatype:

``` Javascript
store.defineType('article', {
  title: { type: String },
  body: { type: String }
});
```

I'm using the postgres adapter:

``` Javascript
var store = fortune({
    adapter: {
        type: postgresAdapter,
        options: {
            url: `postgres://${username}:${password}@${host}:${port}/${db}`,
            generatePrimaryKey: null
        }
    },
    serializers: [{
        type:jsonApi
    }],
    baseUrl: 'http://localhost:4000'
});
```

**Comment by gr0uch** [comment]
Nah this isn't a problem here, it was actually still a bug in the Postgres adapter. I fixed it over there.

**Comment by allthesignals** [comment]
@daliwali what was the issue? I have the latest of the Postgres adapter.

**Comment by allthesignals** [comment]
@daliwali I'm pretty sure it's because I'm not specifying what the ID field is. I'm working with a database whose schema I can't control... so I need to figure out how to alias something into an ID.
