### ISSUE TITLE
Index route promise warning

### ISSUE THREAD

**Issue by yogaraptor** [fortunejs/fortune-json-api#31]
When providing a JSON-API representation of the index route, fortune reports:

```
Warning: a promise was rejected with a non-error: [object Object]
    at processImmediate [as _immediateCallback] (timers.js:383:17)
From previous event:
    at Server.connection (/home/ravenous/dev/mayfly/bikeshop/node_modules/fortune/lib/net/http_server.js:229:6)
    at emitTwo (events.js:87:13)
    at Server.emit (events.js:172:7)
    at HTTPParser.parserOnIncoming [as onIncoming] (_http_server.js:533:12)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:103:23)
```

The request is fulfilled fine, but just curious as to why the index route output is being [thrown as if it were an error](https://github.com/fortunejs/fortune-json-api/blob/master/lib/helpers.js#L96)

**Comment by gr0uch** [comment]
The index route is a hack basically. Either it can make an invalid request to fortune or skip it altogether by throwing.

**Comment by gr0uch** [comment]
This warning is now suppressed by throwing an actual error: https://github.com/fortunejs/fortune-json-api/commit/53d83250be3144a005416a3f85c8ba8d0043a1ce#diff-27a1c86133de4310373decfdad200a91R91

p.s. the JSON API spec doesn't define any index route at all, so this is pretty implementation specific.

**Comment by yogaraptor** [comment]
Nice one! I didn't realise JSON API didn't stipulate an index route; good to know.
