### ISSUE TITLE
Filtering using a field that doesn't exist throws a TypeError

### ISSUE THREAD

**Issue by passcod** [fortunejs/fortune-json-api#5]
```
<-- GET /organisations?filter[badfield]=1                                                                                
xxx GET /organisations?filter[badfield]=1 500 8ms -                                                                      
TypeError: Cannot read property 'type' of undefined                                                                
    at JsonApiSerializer.attachQueries (/home/code/newapi/node_modules/fortune-json-api/dist/lib/helpers.js:300:38)
    at JsonApiSerializer.initializeContext (/home/code/newapi/node_modules/fortune-json-api/dist/lib/helpers.js:90:

    at JsonApiSerializer.processRequest (/home/code/newapi/node_modules/fortune-json-api/dist/lib/index.js:101:43) 
    at SerializerSingleton.proxyMethod (/home/code/newapi/node_modules/fortune/dist/lib/serializer/singleton.js:170

    at /home/code/newapi/node_modules/fortune/dist/lib/dispatch/index.js:87:27                                     
    at run (/home/code/newapi/node_modules/core-js/library/modules/es6.promise.js:89:39)                           
    at /home/code/newapi/node_modules/core-js/library/modules/es6.promise.js:100:28                                
    at flush (/home/code/newapi/node_modules/core-js/library/modules/$.microtask.js:17:13)                         
    at doNTCallback0 (node.js:407:9)                                                                               
    at process._tickCallback (node.js:336:13)                                                                      
```

I expected this to fail more gracefully, perhaps with fortune's own `UnsupportedError`, or just passing the filter data to the adapter without failing. The latter would probably be more useful e.g. for custom processing, as in #2.

**Comment by gr0uch** [comment]
Oops, this should indeed throw a typed error instead of a native one.

**Comment by gr0uch** [comment]
Fixed in commit https://github.com/fortunejs/fortune-json-api/commit/0791351aef8d723a60e8d4a63c63fd4700564d0f.
