### ISSUE TITLE
TypeError: Cannot read property 'replace' of undefined

### ISSUE THREAD

**Issue by lamualfa** [fortunejs/fortune-json-api#72]
Server responds an internal error when client making a call to `localhost:3000/posts?filter=Hello`. I know that the correct format for `filter` query is `?filter[field_name]=value`, but I only do testing to prevent something unexpected. But the server instead produced an error.

Server response:
```json
{
  "jsonapi": {
    "version": "1.0"
  },
  "errors": [
    {
      "title": "Error",
      "detail": "An internal error occurred."
    }
  ]
}
```

Server console:

```bash
(node:33828) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'replace' of undefined
    at underscore (/home/***/Code/nodejs/json-api/node_modules/fortune-json-api/lib/helpers.js:436:12)
    at inflect (/home/***/Code/nodejs/json-api/node_modules/fortune-json-api/lib/helpers.js:401:46)
    at JsonApiSerializer.attachQueries (/home/***/Code/nodejs/json-api/node_modules/fortune-json-api/lib/helpers.js:329:21)
    at JsonApiSerializer.initializeContext (/home/***/Code/nodejs/json-api/node_modules/fortune-json-api/lib/helpers.js:106:17)
    at JsonApiSerializer.processRequest (/home/***/Code/nodejs/json-api/node_modules/fortune-json-api/lib/index.js:94:32)
    at /home/***/Code/nodejs/json-api/node_modules/fortune-http/lib/index.js:294:12
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:33828) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:33828) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:33828) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'replace' of undefined
    at underscore (/home/***/Code/nodejs/json-api/node_modules/fortune-json-api/lib/helpers.js:436:12)
    at inflect (/home/***/Code/nodejs/json-api/node_modules/fortune-json-api/lib/helpers.js:401:46)
    at JsonApiSerializer.attachQueries (/home/***/Code/nodejs/json-api/node_modules/fortune-json-api/lib/helpers.js:329:21)
    at JsonApiSerializer.initializeContext (/home/***/Code/nodejs/json-api/node_modules/fortune-json-api/lib/helpers.js:106:17)
    at JsonApiSerializer.processRequest (/home/***/Code/nodejs/json-api/node_modules/fortune-json-api/lib/index.js:94:32)
    at /home/***/Code/nodejs/json-api/node_modules/fortune-http/lib/index.js:294:12
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:33828) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
```

**Comment by gr0uch** [comment]
Addressed in https://github.com/fortunejs/fortune-json-api/commit/70db2c2e0ea7aad526e15d82368b6fa3c83513ab
