### ISSUE TITLE
"Accept parameters are not allowed" error

### ISSUE THREAD

**Issue by jsepia** [fortunejs/fortune-json-api#8]
I'm using this module as follows:

```
var fortune = require('fortune');
var http = require('http');
var Fortune = require('fortune');
var fortuneJsonApi = require('fortune-json-api');
var store = new Fortune({
    serializers: [{
        type: fortuneJsonApi,
        options: {
            maxLimit: 100
        }
    }]
});

store.defineType('article', {
    title: { type: String },
    body: { type: String },
    lastModified: { type: String }
});

var port = 9770; // DEBUG

var requestListener = fortune.net.http(store);
var server = http.createServer(requestListener);
store.connect().then(function() {
    server.listen(port);
    console.log("Listening on port " + port + "...");
});
```

When accessing any URI on the server I get this error:

```
Unhandled rejection NotAcceptableError: Accept parameters are not allowed.
    at JsonApiSerializer.initializeContext (my-app\node_modules\fortune-json-api\dist\lib\helpers.js:68:83)
    at JsonApiSerializer.processRequest (my-app\node_modules\fortune-json-api\dist\lib\index.js:118:43)
    at proxyMethod (my-app\node_modules\fortune\lib\serializer\singleton.js:139:54)
    at my-app\node_modules\fortune\lib\serializer\singleton.js:112:12
    at my-app\node_modules\fortune\lib\dispatch\index.js:43:37
    at tryCatcher (my-app\node_modules\fortune\node_modules\bluebird\js\release\util.js:11:23)
    at Promise._settlePromiseFromHandler (my-app\node_modules\fortune\node_modules\bluebird\js\release\promise.js:488:31)
    at Promise._settlePromise (my-app\node_modules\fortune\node_modules\bluebird\js\release\promise.js:545:18)
    at Promise._settlePromiseCtx (my-app\node_modules\fortune\node_modules\bluebird\js\release\promise.js:582:10)
    at Async._drainQueue (my-app\node_modules\fortune\node_modules\bluebird\js\release\async.js:130:12)
    at Async._drainQueues (my-app\node_modules\fortune\node_modules\bluebird\js\release\async.js:135:10)
    at Immediate.Async.drainQueues [as _onImmediate] (my-app\node_modules\fortune\node_modules\bluebird\js\release\async.js:16:14)
    at processImmediate [as _immediateCallback] (timers.js:358:17)
```

I am aware that this is supposed to occur if my browser's `accept` header does not allow the JSON API MIME type. But this is the `accept` header being sent:

```
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
```

Both Chrome and Firefox send out this value and it looks good to me (note the `*/*` wildcard at the end). It also doesn't seem to violate [the spec](http://jsonapi.org/format/), which states:

> Servers **MUST** respond with a 406 Not Acceptable status code if a request's Accept header contains the JSON API media type and all instances of that media type are modified with media type parameters.

Why, then, does `fortune-json-api` not accept my `accept` header?

**Comment by gr0uch** [comment]
Ok, so it seems that the spec changed slightly. Previously in the 1.0 release of JSON API, it was explicitly stated that `Accept` header may not contain any parameters. Now it seems that it is more relaxed, so I can remove this check, or PR would be welcome.

**Comment by gr0uch** [comment]
Wait actually, upon reading it again, it hasn't changed.

I interpreted it as the _exact_ media type has to be specified. So `*/*` does not contain the JSON API media type, even though it should match according to the corresponding RFC.

**Comment by jsepia** [comment]
I think I managed to wrap my head around the spec. Feel free to continue this discussion in the PR if needed.
